-- Drop tables if they exist
DROP TABLE IF EXISTS menus;
DROP TABLE IF EXISTS stores;

-- 1. ตาราง stores (ร้านค้า)
CREATE TABLE stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    open_time TIME NOT NULL,
    close_time TIME NOT NULL,
    is_open BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. ตาราง menus (เมนูอาหาร)
CREATE TABLE menus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT REFERENCES stores(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    price INT NOT NULL,
    is_available BOOLEAN DEFAULT true,
    remaining_count INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Realtime
begin;
  -- remove the supabase_realtime publication
  drop publication if exists supabase_realtime;
  -- re-create the supabase_realtime publication with no tables
  create publication supabase_realtime;
commit;
alter publication supabase_realtime add table stores;
alter publication supabase_realtime add table menus;

-- 3. เพิ่มข้อมูลเริ่มต้น (Seed Data)
INSERT INTO stores (id, name, open_time, close_time, is_open) VALUES
(1, 'ร้านป้าแมว', '07:00', '15:00', true),
(2, 'ร้านลุงตู่', '08:00', '14:00', false),
(3, 'ร้านอาหารตามสั่งเจ๊จู', '09:00', '16:00', true);

INSERT INTO menus (store_id, name, description, image_url, price, is_available, remaining_count) VALUES
(1, 'ข้าวกะเพราหมูสับ', 'เผ็ดดุดัน ไม่เกรงใจใคร', 'https://images.unsplash.com/photo-1626074353765-517a681e40be?q=80&w=600&auto=format&fit=crop', 45, true, 20),
(1, 'ข้าวไข่เจียว', 'ไข่ฟู กรอบนอกนุ่มใน', 'https://images.unsplash.com/photo-1615486171434-2e2e71d377b2?q=80&w=600&auto=format&fit=crop', 30, true, 15),
(2, 'มาม่าผัด', 'มาม่าผัดขี้เมา รสเด็ด', 'https://images.unsplash.com/photo-1612929633738-8fe01f7c8166?q=80&w=600&auto=format&fit=crop', 40, false, 0),
(3, 'ข้าวผัดต้มยำ', 'เปรี้ยวเผ็ดจัดจ้าน', 'https://images.unsplash.com/photo-1512058564366-18510be2db19?q=80&w=600&auto=format&fit=crop', 50, true, 10);

-- 4. อัปเดต Sequence ID อัตโนมัติ (ป้องกัน Error 23505)
SELECT setval('stores_id_seq', (SELECT MAX(id) FROM stores));
SELECT setval('menus_id_seq', (SELECT MAX(id) FROM menus));
